version: '3.1'
services:
  django-tutorial:
    container_name: cont-djangotutorial-ic
    image: angelsuarez1612/icdjango
    restart: always
    environment:
      ALLOWED_HOSTS: "*" 
      DB_HOST: django_mariadb-ic
      USER_DJANGO: djangouser
      PASS_DJANGO: djangopass
      BD_DJANGO: djangobd
      DJANGO_SUPERUSER_PASSWORD: admin
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@admin.org
    ports:
      - 8100:8888
    depends_on:
      - db       

  db:
    container_name: django_mariadb-ic
    image: mariadb:10.5
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: djangobd
      MARIADB_USER: djangouser
      MARIADB_PASSWORD: djangopass
    volumes:
      - volume_mariadb_ic:/var/lib/mysql

volumes:
    volume_mariadb_ic:
